pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

polls/urls.py
from django.urls import path

from .views import CreatePollView, ResultsView, VoteView, PollsView

urlpatterns = [
    path('create/', CreatePollView.as_view(), name="createPoll"),
    path('results/<int:pk>', ResultsView.as_view(), name="results"),
    path('vote/<int:pk>', VoteView.as_view(), name="vote"),
    path('polls', PollsView.as_view(), name="polls")
]

quickpoll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('django.contrib.auth.urls')), 
    path('users/', include('users.urls')),
    path('poll/', include('polls.urls')),
]

users/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
from django.urls import reverse


class Poll(models.Model):
    question = models.CharField(max_length=100)
    author = models.CharField(max_length=30)
    time = models.DateTimeField(auto_now_add=True)
    multiple_answers = models.BooleanField(default=False)
    add_answer = models.BooleanField(default=False)

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('home')

class AnswerManager(models.Manager):

    def get_answers(self, pollId):
        return Answer.objects.get_queryset().filter(question_id=pollId)


class Answer(models.Model):
    question_id = models.ForeignKey(Poll, on_delete=models.CASCADE)
    answer = models.CharField(max_length=100)
    count = models.IntegerField(default=0)

    objects = AnswerManager()

    def __str__(self):
        return self.answer

users/models.py
from django.db import models

# Create your models here.

polls/forms.py
from django.forms import ModelForm, TextInput, CharField, Textarea
from django.forms.models import inlineformset_factory

from .models import Answer, Poll

class CreatePollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ['question', 'multiple_answers','add_answer']
        
class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['answer']
        labels = {
            'answer' : '',
        }
        widgets = {
            'answer' : TextInput(attrs={'placeholder' : 'Answer'})
        }

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'home.html'

polls/views.py
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic.edit import CreateView
from django.views.generic import DetailView, ListView
from django.forms import formset_factory
from django.utils import timezone
from django.urls import reverse

from polls.models import Answer, Poll

from .forms import CreatePollForm, AnswerForm

class CreatePollView(CreateView):
    template_name = 'createPoll.html'
    context = {
        'poll_form': CreatePollForm,
        'answer_formset': formset_factory(AnswerForm, extra=3),
    }

    def get(self, request):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        poll_form = self.context['poll_form'](request.POST)
        answer_formset = self.context['answer_formset'](request.POST)
        print(request.POST)
        print(poll_form)
        if poll_form.is_valid() and answer_formset.is_valid():
            poll = poll_form.save()
            for answer in answer_formset:
                Answer(
                    answer = answer.clean()['answer'],
                    question_id= Poll.objects.get(id=poll.id)
                ).save()
            return HttpResponseRedirect('/')
        return render(request, self.template_name) 

class ResultsView(DetailView):
    Model = Poll
    template_name = "results.html"

    queryset = Poll.objects.all()

class VoteView(DetailView):
    Model = Poll
    template_name = "vote.html"
    queryset = Poll.objects.all()

    def post(self, request, *args, **kwargs):
        for key in request.POST:
            if key != 'csrfmiddlewaretoken':
                selected_answer = Answer.objects.get(pk=int(key))
                selected_answer.count += 1
                selected_answer.save()
        return HttpResponseRedirect(reverse('results', args=(kwargs['pk'],)))

class PollsView(ListView):
    Model = Poll
    template_name = "polls.html"
    queryset = Poll.objects.all()

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/Styles.css' %}">
        <title>
            {% block title %}
                Home
            {% endblock title %}
        </title>

    </head>
    <body>

        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a href="{% url 'home' %}" class="navbar-brand ms-3">Home</a>
            <a href="{% url 'polls' %}" class="poll-link">Polls</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarItems" aria-controls="navbarItems" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse me-3" id="navbarItems">
                <ul class="navbar-nav ms-auto" >
                    <form class="form-inline ml-auto">
                        <button class="btn btn-secondary btn-login">
                            <a href="{% url 'login' %}" class="login">
                                Log In
                            </a>
                        </button>
                        <button class="btn btn-primary ml-2 btn-signup">
                            <a href="{% url 'signup' %}" class="signup">
                                Sign Up
                            </a>
                        </button>
                    </form>
                </ul>
            </div>
        </nav>
        
        {% block content %}

        {% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        {% block script %}

        {% endblock script %}
    </body>

</html>

templates/createPoll.html
{% extends 'base.html' %}

{% block title %}
    Create Poll
{% endblock title %}

{% block content %}
<div class="container" id="outer">
    <div id="inner" class="text-center">
        <h1>Create Poll</h1>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="question" maxlength="100" required="" id="id_question" placeholder="Type your question">
            {{ answer_formset.management_form }}
                {% for form in answer_formset %}
                <div class="answer-form">
                    {{ form.as_p }}
                </div>
                {% endfor %}
            <ul class="poll-settings">
                <li>
                    <input type="checkbox" name="multiple_answers" id="id_multiple_answers">
                    <label for="id_multiple_answers">Multiple answers</label>
                </li>
                <li>
                    <input type="checkbox" name="add_answer" id="id_add_answer">    
                    <label for="id_add_answer">Add answer</label>
                </li>
            </ul>

            <button type="submit" class="btn btn-dark">Create Poll</button>

        </form>
    </div>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
<div id="outer">
    <div id="inner">
        <button class="btn-dark create-poll">
            <a href="{% url 'createPoll' %}">Create Poll</a>
        </button>
    </div>
</div>
    
{% endblock content %}

templates/polls.html
{% extends 'base.html' %}

{% block title %}
    Polls
{% endblock title %}


{% block content %}
    <div class="poll-list-container">
        {% for poll in object_list %}
            <h3><a href="{% url 'vote' poll.pk %}" class="poll-links">{{ poll }}</a></h2>
        {% endfor %}
    </div>
{% endblock content %}  

templates/results.html
{% extends 'base.html' %}

{% block title %}
    Poll
{% endblock title %}

{% block content %}
    <h1> {{poll.question}} </h1>

    <ul>
        {% for answer in poll.answer_set.all %}
        <li id="{{answer.id}}">
            {{ answer.answer }} - <span>{{ answer.count }}</span> vote{{ answer.count|pluralize}}
        </li>
        {% endfor %}
    </ul>
{% endblock content %}

{% block script %}
    <script>
        
        let loc = window.location;
        
        let wsStart = 'ws://';
        if (loc.protocol == "https:"){
            wsStart = 'wss://' ;
        } 
        let endpoint = wsStart + loc.host + loc.pathname

        let socket = new WebSocket(endpoint);

        socket.onmessage = function(e){
            console.log("message", e);
            msg = JSON.parse(e.data);
            for (let answer of msg){
                let ans = document.getElementById(answer['pk']).children[0];
                ans.innerHTML = answer['fields']['count'];
                console.log(answer);
            }
        }
        socket.onopen = function(e){
            console.log("open", e);
        }
        socket.onerror = function(e){
            console.log("error", e);
        }
        socket.onclose = function(e){
            socket.close();
            console.log("close", e);
        }
    </script>
{% endblock script %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}
    Sign Up
{% endblock title %}

{% block content %}
<div class="container outer-auth">
    <div class="inner-auth">
        <h1>Sign Up</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark">Sign Up</button>
        </form>
    </div>
</div>
{% endblock content%}

templates/vote.html
{% extends 'base.html' %}

{% block title %}
    Vote
{% endblock title %}

{% block content %}
<h1>{{ poll.question}}</h1>

<form method="post">
    {% csrf_token %}
    {% for answer in poll.answer_set.all %}
        <ul>
            <li>
                {% if poll.multiple_answers %}
                <input type="checkbox" name="{{answer.id}}">
                {% else %}
                <input type="radio" name="{{answer.id}}">
                {% endif %}
                <label for="{{answer.id}}">{{ answer.answer }}</label>
            </li>
        </ul>
    {% endfor %}
    <button type="subimt" class="btn btn-dark"> Vote</button>
    <button class="btn btn-dark"><a href="{% url 'results' poll.pk %}">Results</a></button>

</form>

{% endblock content %}